### ISSUE TITLE
How to pretrain Swin

### ISSUE THREAD

**Issue by 42elenz** [Transconnectome/SwiFT#1]
Hello. Thank you very much for this repo.

We would like to pretrain a fmri model how you did it. 

I was trying to make the pretraining run. But this is not working at the moment. I use this chain of flags:

> TRAINER_ARGS='--accelerator cpu --max_epochs 10 --precision 16 --num_nodes 1 --devices 1 --strategy DDP' # specify the number of gpus as '--devices'
> MAIN_ARGS='--loggername neptune --classifier_module v6 --dataset_name Dummy --image_path {image_path}' 
> DATA_ARGS='--batch_size 8 --num_workers 8  --input_type rest'
> DEFAULT_ARGS='--project_name example-project-tensorflow-keras'
> OPTIONAL_ARGS='--c_multiplier 2 --last_layer_full_MSA True --clf_head_version v1 --downstream_task sex' #--use_scheduler --gamma 0.5 --cycle 0.5' 
> RESUME_ARGS=''
> 
> export NEPTUNE_API_TOKEN="xxxxx"
> 
> export CUDA_VISIBLE_DEVICES=2
> 
> python project/main.py $TRAINER_ARGS $MAIN_ARGS $DEFAULT_ARGS $DATA_ARGS $OPTIONAL_ARGS $RESUME_ARGS \
> --dataset_split_num 1 --seed 1 --learning_rate 5e-5 --model swin4d_ver7 --depth 2 2 6 2 --embed_dim 36 --sequence_length 20 --first_window_size 4 4 4 4 --window_size 4 4 4 4 --img_size 96 96 96 20 --pretraining --use_contrastive --contrastive_type 1

So I am using Dummy. But this is not working with pretraining. Can I not test pretraining with Dummy?
The Error I get here is:
 ```
y, diff_y = fmri
ValueError: too many values to unpack (expected 2)
```

I hope that you can help me with that.

**Comment by Concarne2** [comment]
Thanks for your interest!

The datasets are designed such that if the self.contrastive flag is true, they would return a pair of data. We've updated the dummy dataset to also behave in the same manner, so the issue should be resolved. 
Please let us know if you encounter any more issues.
